export { Footer } from '@/components/Footer'
export { Header } from '@/components/Header'
export { Resume } from '@/components/Resume'
export { Tarot } from '@/components/Tarot'
export { Trip } from '@/components/Trip'
