name: continuous_integration_build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  continuous_integration_build:
    runs-on: ubuntu-latest

    env:
      node_version: current

    steps:
      - name: repository_checkout
        uses: actions/checkout@v4

      - name: pnpm_setup
        uses: pnpm/action-setup@v4

      - name: node_setup<${{ env.node_version }}>
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'

      - name: pnpm_install
        run: pnpm i

      - name: pnpm_lint
        run: pnpm lint

      - name: pnpm_build
        run: pnpm build
